spring.application.name=ChatApplication
spring.mongodb.uri=${MONGODB_URI:mongodb+srv://Krishu:DarkKnight5@krishu0.u1cluzl.mongodb.net/?appName=Krishu0}
spring.mongodb.database=${MONGODB_DATABASE:PracticeMongoDB}
jwt.secret=${JWT_SECRET:Q4c5sP9z2Z4J6mD8xL1wA7nR3vK8tB5eY0qN2hF9sGc=}
allowed.origins=${ALLOWED_ORIGINS:http://localhost:3000}
server.port=${PORT:8080}